// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return null;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // apiKey: "AIzaSyDAiakPZYAqGKv9utpY-xUNWkX-t_Hdwi0",
    // authDomain: "amica-ee087.firebaseapp.com",
    // projectId: "amica-ee087",
    // storageBucket: "amica-ee087.appspot.com",
    // messagingSenderId: "323849334771",
    // appId: "1:323849334771:web:dd02b6cd8471a809356c86"

    // apiKey: "AIzaSyDBFu7D6tjV_8l09U00gXlo0Y1jLSFodH4",
    apiKey: 'AIzaSyDAiakPZYAqGKv9utpY-xUNWkX-t_Hdwi0',
    authDomain: "amica-ee087.firebaseapp.com",
    projectId: "amica-ee087",
    storageBucket: "amica-ee087.appspot.com",
    messagingSenderId: "323849334771",
    appId: "1:323849334771:web:dd02b6cd8471a809356c86",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAiakPZYAqGKv9utpY-xUNWkX-t_Hdwi0',
    appId: '1:323849334771:android:021f2eb36e277ef3356c86',
    messagingSenderId: '323849334771',
    projectId: 'amica-ee087',
    storageBucket: 'amica-d6173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAiakPZYAqGKv9utpY-xUNWkX-t_Hdwi0',
    appId: '1:323849334771:ios:a089d616fef400f8356c86',
    messagingSenderId: '323849334771',
    projectId: 'amica-ee087',
    storageBucket: 'amica-d6173.appspot.com',
    iosClientId:
        '165248862031-g7jt2ijris41uoeg08iibadcdulkpta5.apps.googleusercontent.com',
    iosBundleId: 'com.jaspertech.amica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAiakPZYAqGKv9utpY-xUNWkX-t_Hdwi0',
    appId: '1:165248862031:ios:01834024a1eaa858fd273a',
    messagingSenderId: '323849334771',
    projectId: 'amica-ee087',
    storageBucket: 'amica-ee087.appspot.com',
    // iosClientId:
    //     '165248862031-g7jt2ijris41uoeg08iibadcdulkpta5.apps.googleusercontent.com',
    iosBundleId: 'com.jaspertech.amica',
  );
}



///flutterfire configure --project=chatclone-dd871